# This workflow will publish a package to GitHub Packages using npm, but really it's a Godot addon

name: Godot Package (NPM)

on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: |
          for i in ./*; do
            if [ -d "$i" ]; then
              name=$(jq '.name' $i/package.json)
              version=$(jq '.version' $i/package.json)
              # compare published to what's in the repo
              if [ $(npm show $name version) = $version ]
                npm publish $i
              fi
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
