# This workflow will publish a package to GitHub Packages using npm, but really it's a Godot addon

name: Godot Package (NPM)

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: |
          for i in ./*; do
            if [ -d "$i" ]; then
              npm publish $i
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
